name: Docs Ignore Demo

on:
  push:
    branches:
      - main
      - 'release/*'
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  code-change:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger information
        run: |
          echo "Workflow triggered."
          echo "Branch: ${{ github.ref_name }}"