services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: day36-app

    ports:
      - "3000:3000"

    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - day36-network

  mysql:
    image: mysql:8.4

    container_name: day36-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - day36-network

networks:
  day36-network:
    driver: bridge

volumes:
  mysql_data: