# Stage 1: Build
FROM golang:1.23 AS builder

WORKDIR /app

COPY app/go.mod .
COPY app/main.go .

# Build a static Linux binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server main.go


# Stage 2: Runtime
FROM alpine:3.21

RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup

WORKDIR /app

COPY --from=builder /app/server .

RUN chmod +x /app/server && \
    chown appuser:appgroup /app/server

USER appuser

EXPOSE 8080

CMD ["./server"]